/**
 * Chart marks, as hex literals.
 *
 * SVG `stroke`/`fill` cannot take a Tailwind token, and a Tailwind class built
 * from a variable is never generated by the JIT compiler — so data-driven
 * colour goes through `style={{}}` with the values below, never through an
 * interpolated class name.
 *
 * Note the deliberate split: brand-blue #1a3a8f is correct for text, links and
 * CTAs but is too dark to work as a chart mark beside brand-violet, so marks
 * use the lighter #2649a8 step instead. The two ramps below are monotonic in
 * lightness and anchored on real brand tokens at their dark end.
 */
export const CHART = {
  business: "#2649a8",
  agentic: "#8B5CF6",
  target: "#0f172a",
  benchmark: "#94a3b8",
  grid: "#e2e8f0",
  track: "#f1f5f9",
  surface: "#ffffff",
  positive: "#16a34a",
  negative: "#dc2626",
} as const;

/** brand-soft → brand-blue. */
export const BUSINESS_RAMP = ["#eaf1ff", "#c3d6f7", "#8fadea", "#4c74cc", "#1a3a8f"] as const;

/** violet tint → brand-violet → deep violet. */
export const AGENTIC_RAMP = ["#f3ecfe", "#ddcbfb", "#bda2f7", "#8B5CF6", "#5b30ba"] as const;

export function rampFor(scale: "business" | "agentic") {
  return scale === "business" ? BUSINESS_RAMP : AGENTIC_RAMP;
}

export function markFor(scale: "business" | "agentic") {
  return scale === "business" ? CHART.business : CHART.agentic;
}
